using UnityEngine;
using System.Collections;

public enum MVCPropertyID {
    enMVCPropertyIDNone,
	enClientNet,
    enMainPlayer,
    enNPC,
    enLogin,
    enCardBag,
    enCard,
    enCardEvolution,
    enCardUpdate,
    enSwitchPlayer,
    enStageMenu,
    enMainMenu,
    enSceneManager,
    enBattelSummary,
    enPause,
    enEquipBag,
    enTeam,
    enZone,
    enBattlePropsManager,
    enOperateCardList,
    enExpandBag,
    enRUSure,
    enPopWnd,
	enUserProps,
    enTipMessageBox,
	enMainButtonList,
 	enShopProps,
    enLoading,
    enGuild,
    enFriend,
    enFoundFriendByID,
    enFriendList,
    enApplyList,
	enGameSeting,
    enLeveUp,
	enMessageRespond,
    enLoadingResourcesProp,
    enDebugLog,
    enGachaPanelProp,
    enReward,
    enBaseCardOperateProp,
    enCardDivisionUpdateProp,
    enCardHeardProp,
    enIllustrate,
    enMap,
    enKillTips,

    enActorStartID=1000000,
    enMVCPropertyCount,
}
